"""account

Revision ID: 7bedea4f2832
Revises: 019fca530b88
Create Date: 2026-10-01 19:59:57.249158

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bedea4f2832"
down_revision: str | Sequence[str] | None = "019fca530b88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("holder_kind", sa.String(length=10), nullable=False),
        sa.Column("owner_member_id", sa.UUID(), nullable=True),
        sa.Column("external_holder_id", sa.UUID(), nullable=True),
        sa.Column("closing_day", sa.SmallInteger(), nullable=True),
        sa.Column("due_day", sa.SmallInteger(), nullable=True),
        sa.Column(
            "first_installment_offset",
            sa.SmallInteger(),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(holder_kind = 'external') = (external_holder_id IS NOT NULL)",
            name=op.f("ck_account_external_holder"),
        ),
        sa.CheckConstraint(
            "(holder_kind = 'member') = (owner_member_id IS NOT NULL)",
            name=op.f("ck_account_member_holder"),
        ),
        sa.CheckConstraint(
            "holder_kind IN ('member', 'external')", name=op.f("ck_account_holder_kind")
        ),
        sa.CheckConstraint(
            "kind IN ('checking', 'credit_card', 'store_credit')", name=op.f("ck_account_kind")
        ),
        sa.CheckConstraint(
            "closing_day BETWEEN 1 AND 31", name=op.f("ck_account_closing_day_range")
        ),
        sa.CheckConstraint("due_day BETWEEN 1 AND 31", name=op.f("ck_account_due_day_range")),
        sa.ForeignKeyConstraint(
            ["external_holder_id"],
            ["external_holder.id"],
            name=op.f("fk_account_external_holder_id_external_holder"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_account_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_member_id"],
            ["member.id"],
            name=op.f("fk_account_owner_member_id_member"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_account")),
    )
    op.create_index(
        op.f("ix_account_external_holder_id"), "account", ["external_holder_id"], unique=False
    )
    op.create_index(op.f("ix_account_household_id"), "account", ["household_id"], unique=False)
    op.create_index(
        op.f("ix_account_owner_member_id"), "account", ["owner_member_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_owner_member_id"), table_name="account")
    op.drop_index(op.f("ix_account_household_id"), table_name="account")
    op.drop_index(op.f("ix_account_external_holder_id"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
