"""commitment e entry

Revision ID: 9808f27666c4
Revises: 9fd2e8412e8f
Create Date: 2026-10-02 14:36:33.248278

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9808f27666c4"
down_revision: str | Sequence[str] | None = "9fd2e8412e8f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alvos das FKs compostas de commitment e entry: precisam existir antes delas.
    op.create_unique_constraint("uq_account_id_household_id", "account", ["id", "household_id"])
    op.create_unique_constraint("uq_category_id_household_id", "category", ["id", "household_id"])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "commitment",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("account_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("installment_count", sa.SmallInteger(), nullable=True),
        sa.Column("recurring_amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "status", sa.String(length=10), server_default=sa.text("'active'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'recurring') = (total_amount IS NULL) "
            "AND (kind = 'recurring') = (installment_count IS NULL) "
            "AND (kind = 'recurring') = (recurring_amount IS NOT NULL)",
            name=op.f("ck_commitment_recurring_amounts"),
        ),
        sa.CheckConstraint(
            "end_date IS NULL OR kind = 'recurring'",
            name=op.f("ck_commitment_end_date_only_recurring"),
        ),
        sa.CheckConstraint(
            "kind <> 'single' OR installment_count = 1",
            name=op.f("ck_commitment_single_is_one_installment"),
        ),
        sa.CheckConstraint(
            "kind IN ('installment', 'recurring', 'single')", name=op.f("ck_commitment_kind")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'cancelled', 'settled')", name=op.f("ck_commitment_status")
        ),
        sa.CheckConstraint(
            "end_date >= purchase_date", name=op.f("ck_commitment_end_date_after_start")
        ),
        sa.CheckConstraint(
            "installment_count >= 1", name=op.f("ck_commitment_installment_count_positive")
        ),
        sa.CheckConstraint(
            "recurring_amount > 0", name=op.f("ck_commitment_recurring_amount_positive")
        ),
        sa.CheckConstraint("total_amount > 0", name=op.f("ck_commitment_total_amount_positive")),
        sa.ForeignKeyConstraint(
            ["account_id", "household_id"],
            ["account.id", "account.household_id"],
            name="fk_commitment_account_id_account",
        ),
        sa.ForeignKeyConstraint(
            ["category_id", "household_id"],
            ["category.id", "category.household_id"],
            name="fk_commitment_category_id_category",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_commitment_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_commitment")),
        sa.UniqueConstraint("id", "household_id", name="uq_commitment_id_household_id"),
    )
    op.create_index(op.f("ix_commitment_account_id"), "commitment", ["account_id"], unique=False)
    op.create_index(op.f("ix_commitment_category_id"), "commitment", ["category_id"], unique=False)
    op.create_index(
        op.f("ix_commitment_household_id"), "commitment", ["household_id"], unique=False
    )
    op.create_table(
        "entry",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("commitment_id", sa.UUID(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("seq", sa.SmallInteger(), nullable=False),
        sa.Column("competencia", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "status", sa.String(length=10), server_default=sa.text("'previsto'"), nullable=False
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "source", sa.String(length=10), server_default=sa.text("'manual'"), nullable=False
        ),
        sa.Column("edited_manually", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("idempotency_key", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'pago') = (paid_at IS NOT NULL)", name=op.f("ck_entry_paid_at_iff_pago")
        ),
        sa.CheckConstraint("source IN ('manual', 'fincoach')", name=op.f("ck_entry_source")),
        sa.CheckConstraint(
            "status IN ('previsto', 'confirmado', 'pago')", name=op.f("ck_entry_status")
        ),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM competencia) = 1", name=op.f("ck_entry_competencia_first_day")
        ),
        sa.CheckConstraint("amount >= 0", name=op.f("ck_entry_amount_not_negative")),
        sa.CheckConstraint("seq >= 1", name=op.f("ck_entry_seq_positive")),
        sa.ForeignKeyConstraint(
            ["category_id", "household_id"],
            ["category.id", "category.household_id"],
            name="fk_entry_category_id_category",
        ),
        sa.ForeignKeyConstraint(
            ["commitment_id", "household_id"],
            ["commitment.id", "commitment.household_id"],
            name="fk_entry_commitment_id_commitment",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_entry_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entry")),
        sa.UniqueConstraint(
            "commitment_id", "competencia", name="uq_entry_commitment_id_competencia"
        ),
        sa.UniqueConstraint("commitment_id", "seq", name="uq_entry_commitment_id_seq"),
        sa.UniqueConstraint(
            "household_id", "idempotency_key", name="uq_entry_household_id_idempotency_key"
        ),
    )
    op.create_index("ix_entry_commitment_id", "entry", ["commitment_id"], unique=False)
    op.create_index(
        "ix_entry_household_id_category_id_competencia",
        "entry",
        ["household_id", "category_id", "competencia"],
        unique=False,
    )
    op.create_index(
        "ix_entry_household_id_competencia", "entry", ["household_id", "competencia"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_entry_household_id_competencia", table_name="entry")
    op.drop_index("ix_entry_household_id_category_id_competencia", table_name="entry")
    op.drop_index("ix_entry_commitment_id", table_name="entry")
    op.drop_table("entry")
    op.drop_index(op.f("ix_commitment_household_id"), table_name="commitment")
    op.drop_index(op.f("ix_commitment_category_id"), table_name="commitment")
    op.drop_index(op.f("ix_commitment_account_id"), table_name="commitment")
    op.drop_table("commitment")
    # ### end Alembic commands ###
    op.drop_constraint("uq_category_id_household_id", "category", type_="unique")
    op.drop_constraint("uq_account_id_household_id", "account", type_="unique")
