"""category

Revision ID: 9fd2e8412e8f
Revises: 7bedea4f2832
Create Date: 2026-10-02 12:11:49.905293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fd2e8412e8f"
down_revision: str | Sequence[str] | None = "7bedea4f2832"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Máximo dois níveis (issue #5). Um CHECK não enxerga outra linha, por isso trigger.
# Barra os dois caminhos para o terceiro nível: pendurar uma filha numa subcategoria e
# dar pai a uma categoria que já tem filhas. Filha herda household e direction do pai.
# O FOR SHARE no pai serializa contra um UPDATE concorrente que daria pai a ele.
ENFORCE_HIERARCHY_FUNCTION = """
CREATE FUNCTION category_enforce_hierarchy() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    parent category%ROWTYPE;
BEGIN
    IF NEW.parent_id IS NOT NULL THEN
        SELECT * INTO parent FROM category WHERE id = NEW.parent_id FOR SHARE;
        -- Pai inexistente: a FK rejeita depois.
        IF FOUND THEN
            IF parent.parent_id IS NOT NULL THEN
                RAISE EXCEPTION 'category: terceiro nível não é permitido (pai % é subcategoria)',
                    NEW.parent_id USING ERRCODE = 'check_violation';
            END IF;
            IF parent.household_id <> NEW.household_id THEN
                RAISE EXCEPTION 'category: subcategoria precisa da mesma household do pai'
                    USING ERRCODE = 'check_violation';
            END IF;
            IF parent.direction <> NEW.direction THEN
                RAISE EXCEPTION 'category: subcategoria precisa da mesma direction do pai'
                    USING ERRCODE = 'check_violation';
            END IF;
        END IF;
        IF TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM category WHERE parent_id = NEW.id) THEN
            RAISE EXCEPTION 'category: terceiro nível não é permitido (% tem subcategorias)',
                NEW.id USING ERRCODE = 'check_violation';
        END IF;
    ELSIF TG_OP = 'UPDATE' AND EXISTS (SELECT 1 FROM category WHERE parent_id = NEW.id) THEN
        IF NEW.household_id <> OLD.household_id THEN
            RAISE EXCEPTION 'category: categoria com subcategorias não muda de household'
                USING ERRCODE = 'check_violation';
        END IF;
        IF NEW.direction <> OLD.direction THEN
            RAISE EXCEPTION 'category: categoria com subcategorias não muda de direction'
                USING ERRCODE = 'check_violation';
        END IF;
    END IF;
    RETURN NEW;
END;
$$
"""

# Nenhum delete físico (issue #5): só `archived`. O delete que chega pelo
# ON DELETE CASCADE de household roda dentro do trigger de FK (profundidade > 1) e passa,
# senão apagar uma household com categorias falharia.
PREVENT_DELETE_FUNCTION = """
CREATE FUNCTION category_prevent_delete() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
    IF pg_trigger_depth() > 1 THEN
        RETURN OLD;
    END IF;
    RAISE EXCEPTION 'category: delete físico não é permitido, use archived = true'
        USING ERRCODE = 'restrict_violation';
END;
$$
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("household_id", sa.UUID(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("archived", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('expense', 'income')", name=op.f("ck_category_direction")
        ),
        sa.CheckConstraint("parent_id <> id", name=op.f("ck_category_not_own_parent")),
        sa.ForeignKeyConstraint(
            ["household_id"],
            ["household.id"],
            name=op.f("fk_category_household_id_household"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
            name=op.f("fk_category_parent_id_category"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
        sa.UniqueConstraint(
            "household_id",
            "parent_id",
            "name",
            name="uq_category_household_id_parent_id_name",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(op.f("ix_category_household_id"), "category", ["household_id"], unique=False)
    op.create_index(op.f("ix_category_parent_id"), "category", ["parent_id"], unique=False)
    # ### end Alembic commands ###
    op.execute(ENFORCE_HIERARCHY_FUNCTION)
    op.execute(
        "CREATE TRIGGER category_enforce_hierarchy "
        "BEFORE INSERT OR UPDATE OF parent_id, household_id, direction ON category "
        "FOR EACH ROW EXECUTE FUNCTION category_enforce_hierarchy()"
    )
    op.execute(PREVENT_DELETE_FUNCTION)
    op.execute(
        "CREATE TRIGGER category_prevent_delete BEFORE DELETE ON category "
        "FOR EACH ROW EXECUTE FUNCTION category_prevent_delete()"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_category_parent_id"), table_name="category")
    op.drop_index(op.f("ix_category_household_id"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION category_prevent_delete()")
    op.execute("DROP FUNCTION category_enforce_hierarchy()")
